#!/usr/bin/env python3
"""Deterministically fit and materialize v1.3 R4 B500 action-head candidates."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import math
import os
from pathlib import Path
import shutil
import stat
import time
from typing import Any, Mapping

import torch
import torch.nn.functional as F


ROOT = Path("/home/lxq/Softwares/robot_lab")
PREREGISTRATION = ROOT / "tmp/highstep_student_recovery_v13_20260713/r4_preregistration.json"
PREREGISTRATION_SHA256 = "8f43112e94fbe032fd4d640292151210b692c3f853d460a98a0456fb0ed7b45e"
B500 = ROOT / (
    "logs/rsl_rl/arclab_arcdog_adjustable_leg_highstep_action_score_vae_"
    "student_no_prior_Student/2026-07-12_23-55-22_student_recovery_v111_"
    "B500_20260712_235515/model_498.pt"
)
B500_SHA256 = "f76c8ff2b772c1868b8a97b505febc09ad1f0ece7b5080a748f20e80101eb159"
ACTOR_HEAD_NAMES = ("actor.6.weight", "actor.6.bias")
# The replay was generated by per-frame CUDA forward while the deterministic
# fit reconstructs frozen features with batched CPU GEMM.  This tolerance is
# only an input-integrity check for that cross-device numerical roundoff; it is
# 100x tighter than the immutable 0.002 success-anchor candidate gate.
ANCHOR_RECONSTRUCTION_ATOL = 2.0e-5


def sha256_file(path: os.PathLike[str] | str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_json(path: Path, payload: Mapping[str, Any], *, read_only: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    temporary.write_text(
        json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, path)
    if read_only:
        path.chmod(stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)


def _load_authority(dataset_manifest: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    if sha256_file(PREREGISTRATION) != PREREGISTRATION_SHA256 or PREREGISTRATION.stat().st_mode & 0o222:
        raise RuntimeError("R4 preregistration SHA/read-only binding failed")
    prereg = json.loads(PREREGISTRATION.read_text(encoding="utf-8"))
    if sha256_file(B500) != B500_SHA256:
        raise RuntimeError("R4 B500 anchor changed")
    dataset_manifest = dataset_manifest.resolve(strict=True)
    if dataset_manifest.stat().st_mode & 0o222:
        raise RuntimeError("R4 dataset manifest must be read-only")
    dataset = json.loads(dataset_manifest.read_text(encoding="utf-8"))
    if not (
        dataset.get("kind") == "highstep_v13_b500_core9_replay_dataset"
        and dataset.get("workflow_id") == prereg["workflow_id"]
        and dataset.get("preregistration_sha256") == PREREGISTRATION_SHA256
        and dataset.get("matrix_complete") is True
        and dataset.get("total_frames") == 5400
        and len(dataset.get("trajectories") or []) == 9
    ):
        raise RuntimeError("R4 dataset manifest contract failed")
    return prereg, dataset


def _actor_hidden(inputs: torch.Tensor, state: Mapping[str, torch.Tensor]) -> torch.Tensor:
    value = inputs
    for index in (0, 2, 4):
        value = F.elu(F.linear(value, state[f"actor.{index}.weight"], state[f"actor.{index}.bias"]))
    if value.shape[1] != 128:
        raise RuntimeError("R4 actor penultimate feature dimension changed")
    return value


def _audit_anchor_reconstruction(
    reconstructed: torch.Tensor, anchor: torch.Tensor, run_id: str
) -> dict[str, float | str]:
    error = torch.abs(reconstructed - anchor)
    maximum = float(torch.max(error).item())
    mean = float(torch.mean(error).item())
    if not math.isfinite(maximum) or maximum > ANCHOR_RECONSTRUCTION_ATOL:
        raise RuntimeError(
            f"R4 B500 action reconstruction failed: {run_id} "
            f"max_abs={maximum} tolerance={ANCHOR_RECONSTRUCTION_ATOL}"
        )
    return {
        "run_id": run_id,
        "max_abs": maximum,
        "mean_abs": mean,
        "tolerance": ANCHOR_RECONSTRUCTION_ATOL,
    }


def _read_dataset(
    dataset: Mapping[str, Any], state: Mapping[str, torch.Tensor]
) -> dict[str, Any]:
    hidden_parts: list[torch.Tensor] = []
    anchor_parts: list[torch.Tensor] = []
    teacher_parts: list[torch.Tensor] = []
    target_parts: list[torch.Tensor] = []
    weight_parts: list[torch.Tensor] = []
    success_parts: list[torch.Tensor] = []
    trajectory_names: list[str] = []
    phase_names: list[str] = []
    reconstruction_audits: list[dict[str, float | str]] = []
    for item in dataset["trajectories"]:
        frames_path = Path(item["frames"]).resolve(strict=True)
        if sha256_file(frames_path) != item["frames_sha256"]:
            raise RuntimeError(f"R4 frames changed: {frames_path}")
        records = [json.loads(line) for line in frames_path.read_text(encoding="utf-8").splitlines()]
        if len(records) != 600:
            raise RuntimeError(f"R4 trajectory is not 600 frames: {item['run_id']}")
        policy = torch.tensor([row["policy_observations"] for row in records], dtype=torch.float32)
        latent = torch.tensor([row["student_latent_clamped"] for row in records], dtype=torch.float32)
        anchor = torch.tensor([row["student_action"] for row in records], dtype=torch.float32)
        teacher = torch.tensor(
            [row["teacher_action_post_prior_raw_equivalent"] for row in records],
            dtype=torch.float32,
        )
        hidden = _actor_hidden(torch.cat((policy, latent), dim=1), state)
        reconstructed = F.linear(hidden, state["actor.6.weight"], state["actor.6.bias"])
        reconstruction_audits.append(
            _audit_anchor_reconstruction(reconstructed, anchor, str(item["run_id"]))
        )
        success = item["role"] == "success_anchor"
        target = anchor if success else teacher
        phases: dict[str, list[int]] = {}
        for index, row in enumerate(records):
            phases.setdefault(str(row["phase"]), []).append(index)
        base_weights = torch.zeros(600, dtype=torch.float64)
        for indices in phases.values():
            base_weights[indices] = 1.0 / (len(phases) * len(indices))
        role_multiplier = 20.0 if success else 1.0
        weights = role_multiplier * base_weights
        hidden_parts.append(hidden.double())
        anchor_parts.append(anchor.double())
        teacher_parts.append(teacher.double())
        target_parts.append(target.double())
        weight_parts.append(weights)
        success_parts.append(torch.full((600,), success, dtype=torch.bool))
        trajectory_names.extend([item["run_id"]] * 600)
        phase_names.extend([str(row["phase"]) for row in records])
    return {
        "hidden": torch.cat(hidden_parts),
        "anchor": torch.cat(anchor_parts),
        "teacher": torch.cat(teacher_parts),
        "target": torch.cat(target_parts),
        "weights": torch.cat(weight_parts),
        "success": torch.cat(success_parts),
        "trajectory_names": trajectory_names,
        "phase_names": phase_names,
        "anchor_reconstruction_audits": reconstruction_audits,
    }


def _weighted_ridge(
    hidden: torch.Tensor,
    target: torch.Tensor,
    weights: torch.Tensor,
    theta0: torch.Tensor,
    ridge_lambda: float,
) -> torch.Tensor:
    x = torch.cat((hidden, torch.ones((hidden.shape[0], 1), dtype=torch.float64)), dim=1)
    sqrt_w = torch.sqrt(weights).unsqueeze(1)
    xw = x * sqrt_w
    yw = target * sqrt_w
    identity = torch.eye(x.shape[1], dtype=torch.float64)
    matrix = xw.T @ xw + float(ridge_lambda) * identity
    rhs = xw.T @ yw + float(ridge_lambda) * theta0
    theta = torch.linalg.solve(matrix, rhs)
    if not bool(torch.isfinite(theta).all().item()):
        raise RuntimeError(f"R4 ridge solution is non-finite at lambda={ridge_lambda}")
    return theta


def _statistics(data: Mapping[str, Any], candidate: torch.Tensor) -> dict[str, Any]:
    anchor = data["anchor"]
    teacher = data["teacher"]
    success = data["success"]
    failure = ~success
    success_mae = float(torch.mean(torch.abs(candidate[success] - anchor[success])).item())
    baseline_failure = float(torch.mean(torch.abs(anchor[failure] - teacher[failure])).item())
    candidate_failure = float(torch.mean(torch.abs(candidate[failure] - teacher[failure])).item())
    reduction = (baseline_failure - candidate_failure) / max(baseline_failure, 1.0e-12)
    abs_drift = torch.abs(candidate - anchor)
    joint_q99 = [float(torch.quantile(abs_drift[:, index], 0.99).item()) for index in range(16)]
    max_q99 = max(joint_q99)
    return {
        "success_anchor_raw_action_mae": success_mae,
        "failure_teacher_raw_action_mae_baseline": baseline_failure,
        "failure_teacher_raw_action_mae_candidate": candidate_failure,
        "failure_teacher_mae_relative_reduction": reduction,
        "anchor_abs_error_q99_by_joint": joint_q99,
        "anchor_abs_error_q99_max": max_q99,
        "all_outputs_finite": bool(torch.isfinite(candidate).all().item()),
        "offline_gate_passed": bool(
            success_mae <= 0.002
            and reduction >= 0.10
            and max_q99 <= 0.02
            and bool(torch.isfinite(candidate).all().item())
        ),
    }


def _materialize_candidate(
    *,
    payload: Mapping[str, Any],
    theta: torch.Tensor,
    ridge_lambda: float,
    statistics: Mapping[str, Any],
    dataset_manifest: Path,
    output_root: Path,
) -> dict[str, Any]:
    label = f"lambda_{ridge_lambda:.0e}".replace("+", "")
    run_dir = output_root / label
    if run_dir.exists():
        manifest_path = run_dir / "candidate_manifest.json"
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        checkpoint = Path(manifest["checkpoint"]).resolve(strict=True)
        if manifest.get("checkpoint_sha256") != sha256_file(checkpoint):
            raise RuntimeError(f"existing R4 candidate changed: {run_dir}")
        return manifest
    (run_dir / "params").mkdir(parents=True)
    candidate_payload = copy.deepcopy(payload)
    candidate_state = candidate_payload["model_state_dict"]
    candidate_state["actor.6.weight"] = theta[:128].T.to(
        dtype=candidate_state["actor.6.weight"].dtype
    )
    candidate_state["actor.6.bias"] = theta[128].to(
        dtype=candidate_state["actor.6.bias"].dtype
    )
    infos = candidate_payload.setdefault("infos", {})
    infos["highstep_v13_r4"] = {
        "schema_version": 1,
        "stage": "R4",
        "workflow_id": "highstep_student_recovery_v13_20260713",
        "preregistration": str(PREREGISTRATION.resolve()),
        "preregistration_sha256": PREREGISTRATION_SHA256,
        "dataset_manifest": str(dataset_manifest.resolve()),
        "dataset_manifest_sha256": sha256_file(dataset_manifest),
        "anchor_checkpoint": str(B500.resolve()),
        "anchor_checkpoint_sha256": B500_SHA256,
        "ridge_lambda": ridge_lambda,
        "trainable_tensors": list(ACTOR_HEAD_NAMES),
        "statistics": dict(statistics),
    }
    checkpoint = run_dir / "model_498.pt"
    temporary = run_dir / f".model_498.pt.{os.getpid()}.tmp"
    torch.save(candidate_payload, temporary)
    os.replace(temporary, checkpoint)
    checkpoint_sha = sha256_file(checkpoint)
    source_params = B500.parent / "params"
    for name in ("agent.yaml", "env.yaml", "highstep_schedule_manifest.json"):
        shutil.copyfile(source_params / name, run_dir / "params" / name)
    runtime = json.loads((source_params / "highstep_runtime_state.json").read_text())
    source_snapshot = next(
        item for item in runtime["snapshots"] if item["checkpoint_file"] == B500.name
    )
    candidate_snapshot = copy.deepcopy(source_snapshot)
    candidate_snapshot["checkpoint_file"] = checkpoint.name
    candidate_snapshot["checkpoint_sha256"] = checkpoint_sha
    candidate_snapshot["created_at"] = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    atomic_json(
        run_dir / "params/highstep_runtime_state.json",
        {"context": "train", "schema_version": 2, "snapshots": [candidate_snapshot]},
    )
    binding = {
        "schema_version": 1,
        "kind": "highstep_v13_r4_candidate_binding",
        "workflow_id": "highstep_student_recovery_v13_20260713",
        "checkpoint": str(checkpoint.resolve()),
        "checkpoint_sha256": checkpoint_sha,
        "anchor_checkpoint": str(B500.resolve()),
        "anchor_checkpoint_sha256": B500_SHA256,
        "preregistration": str(PREREGISTRATION.resolve()),
        "preregistration_sha256": PREREGISTRATION_SHA256,
        "dataset_manifest": str(dataset_manifest.resolve()),
        "dataset_manifest_sha256": sha256_file(dataset_manifest),
        "ridge_lambda": ridge_lambda,
        "trainable_tensors": list(ACTOR_HEAD_NAMES),
        "frozen_tensor_violation_count": 0,
        "statistics": dict(statistics),
    }
    binding_path = run_dir / "params/highstep_v13_r4_binding.json"
    atomic_json(binding_path, binding, read_only=True)
    manifest = {
        **binding,
        "kind": "highstep_v13_r4_candidate_manifest",
        "run_dir": str(run_dir.resolve()),
        "runtime_state": str((run_dir / "params/highstep_runtime_state.json").resolve()),
        "runtime_state_sha256": sha256_file(run_dir / "params/highstep_runtime_state.json"),
        "schedule_manifest": str((run_dir / "params/highstep_schedule_manifest.json").resolve()),
        "schedule_manifest_sha256": sha256_file(run_dir / "params/highstep_schedule_manifest.json"),
        "binding": str(binding_path.resolve()),
        "binding_sha256": sha256_file(binding_path),
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
    }
    manifest_path = run_dir / "candidate_manifest.json"
    atomic_json(manifest_path, manifest, read_only=True)
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset-manifest", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    args = parser.parse_args()
    dataset_manifest = args.dataset_manifest.resolve(strict=True)
    prereg, dataset = _load_authority(dataset_manifest)
    payload = torch.load(B500, map_location="cpu", weights_only=False)
    state = payload["model_state_dict"]
    data = _read_dataset(dataset, state)
    theta0 = torch.cat(
        (state["actor.6.weight"].double().T, state["actor.6.bias"].double().unsqueeze(0)),
        dim=0,
    )
    output_root = args.output_root.resolve()
    output_root.mkdir(parents=True, exist_ok=True)
    manifests: list[dict[str, Any]] = []
    for ridge_lambda in prereg["r4_fit"]["ridge_lambdas"]:
        theta = _weighted_ridge(
            data["hidden"], data["target"], data["weights"], theta0, float(ridge_lambda)
        )
        design = torch.cat(
            (data["hidden"], torch.ones((data["hidden"].shape[0], 1), dtype=torch.float64)),
            dim=1,
        )
        candidate = design @ theta
        statistics = _statistics(data, candidate)
        manifests.append(
            _materialize_candidate(
                payload=payload,
                theta=theta,
                ridge_lambda=float(ridge_lambda),
                statistics=statistics,
                dataset_manifest=dataset_manifest,
                output_root=output_root,
            )
        )
    safe = [item for item in manifests if item["statistics"]["offline_gate_passed"]]
    safe.sort(
        key=lambda item: (
            -float(item["statistics"]["failure_teacher_mae_relative_reduction"]),
            float(item["statistics"]["success_anchor_raw_action_mae"]),
            float(item["statistics"]["anchor_abs_error_q99_max"]),
            float(item["ridge_lambda"]),
        )
    )
    report = {
        "schema_version": 1,
        "kind": "highstep_v13_r4_offline_feasibility",
        "workflow_id": prereg["workflow_id"],
        "preregistration": str(PREREGISTRATION.resolve()),
        "preregistration_sha256": PREREGISTRATION_SHA256,
        "dataset_manifest": str(dataset_manifest),
        "dataset_manifest_sha256": sha256_file(dataset_manifest),
        "candidate_count": len(manifests),
        "safe_candidate_count": len(safe),
        "head_only_feasible": bool(safe),
        "candidate_manifests": [
            {
                "ridge_lambda": item["ridge_lambda"],
                "manifest": str(Path(item["run_dir"]) / "candidate_manifest.json"),
                "manifest_sha256": sha256_file(Path(item["run_dir"]) / "candidate_manifest.json"),
                "statistics": item["statistics"],
            }
            for item in manifests
        ],
        "safe_candidate_order": [
            {
                "ridge_lambda": item["ridge_lambda"],
                "checkpoint": item["checkpoint"],
                "checkpoint_sha256": item["checkpoint_sha256"],
            }
            for item in safe
        ],
        "anchor_reconstruction_audits": data["anchor_reconstruction_audits"],
        "completed_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
    }
    atomic_json(output_root / "r4_offline_feasibility.json", report, read_only=True)
    print(json.dumps({"head_only_feasible": bool(safe), "safe_candidate_count": len(safe)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
